version: '3.9'

services:
  mysqlcontainer:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: demo_crawl
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3336:3306"
    networks:
      - base
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 5
      timeout: 20s

  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu_container
    command: sleep infinity
    networks:
      - base
    volumes:
      - .:/data
    stdin_open: true
    tty: true

  selenium:
    # image: seleniarm/standalone-chromium
    image: ${SELENIUM_IMAGE}
    container_name: selenium
    shm_size: 2g 
    ports:
      - "4444:4444"
    networks:
      - base
  
  web:
    platform: linux/arm64
    build: .
    command: bash -c "poetry run scrapy crawl example"
    container_name: demo
    environment:
      - SELENIUM_HOST=selenium
      - MYSQL_HOST=mysqlcontainer
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=demo_crawl
    volumes:
      - .:/app
    working_dir: /app/myspider
    ports:
      - "8000:8000"
    depends_on:
      - mysqlcontainer
      - selenium
    networks:
      - base

networks:
  base:
